version: '3.8'
services:
  app:
    image: shinji19/astar-dev:1.0.4
    working_dir: /opt/lepus
    ports:
      # ui
      - 3000:3000
      # astar localnode(tcp)
      - 9933:9933
      # astar localnode(ws)
      - 9944:9944
    volumes:
      - ./:/opt/lepus
    tty: true
