specVersion: 1.0.0
name: subql-lepus
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=1.0.0"
  query:
    name: "@subql/query"
    version: "*"
description: This SubQuery project can be use as a starting point for Astar network
repository: "https://github.com/subquery/subql-starter"
schema:
  file: ./schema.graphql
network:
  chainId: "0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6"
  endpoint: "wss://astar.api.onfinality.io/public-ws"
  dictionary: "https://api.subquery.network/sq/subquery/astar-dictionary"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1000000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleNewEraEvent
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: NewDappStakingEra